@startuml
class BaudBag
class Config
class Cache

enum BagSetType {
    Backpack,
    Bank,
    GuildBank,
    VoidStorage
}

class BagSet {
    BagSetType Type
    PerformInitialBuild()
    ApplyConfiguration()
}

enum ContainerType {
    Joined,
    Tabbed
}

class Container {
    ContainerType Type
    Update()
    SaveCoordinates()
}
class SubContainer{
    number ContainerId
    Update()
}

note left of SubContainer : this represents a "Bag" in WoW, see DevReadMe.txt

BaudBag *-- Config
BaudBag *-- Cache
BaudBag *-- BagSet

BagSet *-- Container
BagSet *-- SubContainer
Container *-- SubContainer
@enduml