@startuml addon initialization phase

participant WoW

WoW -> WoW: load all files in toc
activate WoW
    WoW -> WoW: call OnLoad on any frame directly intantiated (excludes virtuals)

    create BaudBagContainer6_1
    WoW -> BaudBagContainer6_1: OnLoad()

    create BaudBagOptions
    WoW -> BaudBagOptions: OnLoad()

    create BaudBagContainer1_1
    WoW -> BaudBagContainer1_1: OnLoad()

    create BaudBagContainer2_1
    WoW -> BaudBagContainer2_1: OnLoad()

    create BaudBagFrame
    WoW -> BaudBagFrame: BaudBagFrame_OnLoad(self, event, ...)
    activate BaudBagFrame
        BaudBagFrame -> BaudBagFrame: call hook ExtendBaseTypes
        BaudBagFrame -> BaudBagFrame: call Init() on all BagSetTypes

        BaudBagFrame -> BaudBagFrame: event init stuff (TODO: rework!)

        BaudBagFrame -> BaudBagFrame: BaudBagContainerX_1 initial setup (as not done by CreateContainer)

        create BagSet
        BaudBagFrame -> BagSet: AddOnTable:CreateBagSet(...) [for backpack & banks]
        BaudBagFrame -> BaudBagFrame: call hook InitBagSets
        BaudBagFrame -> BagSet: PerformInitialBuild [for backpack & banks]

        activate BagSet
            create Container
            BagSet -> Container: new

            create SubContainer
            BagSet -> SubContainer: new
            BagSet -> BagSet: tinsert subcontainer into internal list
        deactivate BagSet

        BaudBagFrame -> BaudBagFrame: call hook EssentialsLoaded
    deactivate BaudBagFrame


    WoW -> BaudBagFrame: event ADDON_LOADED
    activate BaudBagFrame
        BaudBagFrame -> BaudBagFrame: AddOnTable:InitCache()
        BaudBagFrame -> BaudBagFrame: AddOnTable:RegisterDefaultBackgrounds()
    deactivate BaudBagFrame

    WoW -> BaudBagFrame: event PLAYER_LOGIN
    activate BaudBagFrame
        BaudBagFrame -> BaudBagFrame: BackpackBagOverview_Initialize()
        BaudBagFrame -> BaudBagFrame: BaudBagUpdateFromBBConfig()
        BaudBagFrame -> BaudBagFrame: BaudBagBankBags_Initialize()
        BaudBagFrame -> BaudBagFrame: AddOnTable:UpdateBankParents()
        BaudBagFrame -> BaudBagFrame: AddOnTable:UpdateBagParents()
    deactivate BaudBagFrame

deactivate WoW
@enduml